name = "Example"
uuid = "d25d414a-8a25-4ed4-b765-7496cad70195"
authors = ["Ruby Jiang"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
